version: 2

sources:
  - name: raw
    database: boc-fx-analytics
    schema: raw
    tables:
      - name: boc_fx_observations
        description: "Bank of Canada Valet FX observations loaded by Python ingestion."
        loaded_at_field: ingested_at
        config:
          freshness:
            warn_after: {count: 2, period: day}
            error_after: {count: 7, period: day}
